version: '2'
services:
  docker-node:
    build: .
    command: npm start
    container_name: docker-node
    volumes:
      - .:/app
    ports:
      - '8080:8080'
networks:
  default:
    external:
      name: docker-graphql